### ISSUE TITLE
Consulta CNPJ Receita

### ISSUE THREAD

**Issue by ThalisonSantos** [ACBrNet/ACBr.Net.Consulta#10]
com a mudança do captcha da receita ainda vai ser possível utilizar a biblioteca ou vai ser atualizada?

**Comment by rftd** [comment]
provavelmente não vai ser possível utilizar mais, pois a receita esta usando recaptcha agora.

**Comment by ThalisonSantos** [comment]
@rftd mas notei que ela continuou com o outro modo só que com um link diferente
https://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/Cnpjreva_solicitacao3.asp

**Comment by ThalisonSantos** [comment]
Boa tarde @rftd 
conseguiu verificar esse link que passei?

**Comment by rftd** [comment]
Este link esta instável hora funciona hora não.

**Comment by guimagcpd** [comment]
boa noite tudo bem ? espero que sim. Este recurso então não será mais disponibilizado pela biblioteca ?

**Comment by rftd** [comment]
Este recurso depende do link do governo assim que ele estabilizar as coisas e se estabilizar vai funcionar, caso contrario não tem muito o que posso fazer.
