### ISSUE TITLE
A validação anti-robô não foi realizada corretamente

### ISSUE THREAD

**Issue by guialexandree** [ACBrNet/ACBr.Net.Consulta#13]
Estou tendo como resposta sempre "A validação anti-robô não foi realizada corretamente. Por favor, tente novamente.", alguem sabe o que pode ser?
 Estou utilizando as urls:
this.UrlBase = "https://www.receita.fazenda.gov.br/Aplicacoes/SSL/ATCTA/CPF/";
                this.UrlCaptcha = "captcha/gerarCaptcha.asp?data=" + Segundos(); // Função segundos traz millisegundos 01/01/1970 até data atual
                this.UrlConsulta = "ConsultaSituacao/ConsultaPublicaExibir.asp";
                this.UrlPrincipal = "ConsultaPublica.asp";

E como parametros :
string parametros =
                            "idCheckedReCaptcha=true&" +
                            "TxtCPF=XXX.XXX.XXX-XX&" +
                            "txtDataNascimento=22/02/1993&" +
                            "txtToken_captcha_serpro_gov_br=&" +
                            "txtTexto_captcha_serpro_gov_br=" + Captcha+ "&" +
                            "Enviar=Consultar";

**Comment by rftd** [comment]
@guialexandree este erro ocorrendo onde no código da biblioteca ? este código não parecer ser o nosso.
