### ISSUE TITLE
A lib ainda funciona? 

### ISSUE THREAD

**Issue by rafaneri** [ACBrNet/ACBr.Net.Consulta#15]
O método GetCaptcha está retornando erro 403.

**Comment by rftd** [comment]
cara é complicado o site do governo ficou instavel teve varias modificações e eu não tive tempo de atualizar a mesma, por equanto apenas o cep funciona

**Comment by rafaneri** [comment]
Valeu! Vou tentar atualizar, as url's mudaram. Está retornando 403, não sei se é o referrer, vou tentar colocar para funcionar.

**Comment by Bertrak** [comment]
Oi, boa tarde, conseguiu resolver o 403?
