### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by patricklcb** [ACBrNet/ACBr.Net.Consulta#16]
Haveria a possibilidade de disponibilizar alguns exemplos para as consultas? Sou estudante e estou tendo certa dificuldade em aplicar. Se tiver a possibilidade, agradeço muito!

**Comment by rftd** [comment]
Tem exemplos no fontes, mas as consultas de CPF e CNPJ estão com problemas devido a modificações feita no site da receita.

**Comment by patricklcb** [comment]
> Tem exemplos no fontes, mas as consultas de CPF e CNPJ estão com problemas devido a modificações feita no site da receita.

Obrigado!!
