### ISSUE TITLE
Consulta CPF com erro

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.Consulta#17]
Acabei de baixar o projeto e na hora que fui testar a unica que não funcionou foi a consulta de CPF que na hora que abre a tela de digitar o captcha da erro.

**Comment by leandrossantos** [comment]
Não entendi, porque fechou e não falou nada?

**Comment by marcussacana** [comment]
Ninguém gosta de colecionar issues no seu repositório haha
