### ISSUE TITLE
Sintegra MT/BA

### ISSUE THREAD

**Issue by guimagcpd** [ACBrNet/ACBr.Net.Consulta#7]
Bom dia, uso sua DLL em meu sistema e acho fantástica.
Qual a previsão para implementar o estado do MT e BA na consulta Sintegra ?
Desde ja´agradeço  atenção

**Comment by rftd** [comment]
Eu precisaria de CNPJ e IE dos estados para implementar.

**Comment by guimagcpd** [comment]
Ótimo
Seguem...
Bahia CNPJ = 07757360000181
Bahia IE = 67869512ME

MT CNPJ = 02422951000184
IE = 131804812

Desde já agradeço...Muito Obrigado.

**Comment by rftd** [comment]
Testa pelo branch de desenvolvimento.
Obs.: Sintegra de MT o captcha as vezes mesmo estando certo da errado até na pagina deles.

**Comment by guimagcpd** [comment]
Blz vou testar e te posiciono obrigado...

**Comment by guimagcpd** [comment]
Boa noite, testei aqui, adicionei o conteudo e as classes novas e testando ja obtive um erro no MT
Ocorreu uma exceção do tipo "ACBr.Net.Core.ACBrException" em ACBr.Net.Consulta.dll, mas ela não foi manipulada no código do usuário

Informações adicionais: Erro ao processar retorno.

Sera que eu deixei algo de fora...
?

**Comment by guimagcpd** [comment]
Consegui ver um detalhe aqui
no mt debugando..
a razão social

no código está
Raz?o social
N?mero
Munic?pio/UF
Atividade Econ?mica

e no retorno está
Razão social
Número
Município/UF
Atividade Económica


Resumindo creio que neste estado se alinhar a parte dos acentos e caracteres ja deva resolver né...
?, eu não entendo muito de C# , então pode ser que eu esteja enganado, mais desde já agradeço seu empenho.... quando tiver correções se puder comunicar agradeço desde já.. boa noite..


AH ia me esquecendo... se não for pedir de mais e já pedindo...
Tenho mais 3 estados que lembrei que tenho um cliente em cada, se for possível add.. como sempre... te agradeço muito...e parabéns, esse projeto é simplesmente perfeito...
RO = CNPJ  = 07138435000146
PI  =  CNPJ    = 10933245000125
PR = CNPJ =  22237889000168

**Comment by rftd** [comment]
Estes erros acima não ocorreram aqui você esta usando a versão do Branch de dev ?

**Comment by guimagcpd** [comment]
Bom dia, então, eu realmente entendo bem pouco quase nada de C#, e sou bem novo neste lance de Nuget, github.com, , desculpe estou sendo muito sincero, entendo quase nada mesmo, pra vc ter uma ideia pra eu conseguir fazer os testes fui abrindo uma a uma das partes aqui no site mesmo e sobrepondo o código no projeto inteiro baixado via bloco de notas, porque não consegui baixar ele inteiro com os ajustes pra testar... pode ser sim que eu com certeza tenha feito coisa errada... Teria alguma forma de disponibilizar o projeto normal , da forma como baixamos quando acessamos o site,.. porque eu não encontrei uma forma de baixar ele do jeito que falou, ai tive que adaptar aqui pra conseguir testar, e talvez,por isso dos erros que eu te falei...

**Comment by rftd** [comment]
Vamos por partes.
1º Nuget é o pacote já compilado e funcionado disponibilizado para poder ser baixado direto do VS.
2º Github é um site que possibilita a criação de repositório GIT, para baixar o código fonte você pode usar o botão download do repositório ou usar um GIT client. EX.: [Tortoise Git Client](https://augustopierzynski.wordpress.com/2013/10/16/instalando-o-tortoise-git-para-windows/).
3º Em cima do código na pagina inicial do repositório você pode escolher o branch que você esta querendo baixar.

Recomendo leitura sobre o GIT para entender o funcionamento do repositório.
