### ISSUE TITLE
Adicionar sintegra para RO, PI e PR

### ISSUE THREAD

**Issue by rftd** [ACBrNet/ACBr.Net.Consulta#8]
Conforme solicitado na issue #7 por @guimagcpd 

Adicionar sintegra para RO, PI e PR

RO = CNPJ = 07138435000146
PI = CNPJ = 10933245000125
PR = CNPJ = 22237889000168

**Comment by guimagcpd** [comment]
Muito Obrigado pelas explicações... e pelo apoio..
vou aprender rsrs , uma hra aprendo rs, outra dúvida quando aparecer estas atualizações de RP PI e PR eu sou avisado por aqui ? é assim que funciona né. ?

**Comment by rftd** [comment]
Eu analisei os sites sintegra dos estados solicitados e o de Rondônia não sera possivel fazer devido ao tipo de captcha utilizado por eles.

**Comment by guimagcpd** [comment]
Boa tarde Rafael tudo bem, espero que sim..
Mais os demais estados que passei com exceção de RO será possível ? 
Obrigado desde já.

**Comment by ThalisonSantos** [comment]
seria possível inserir a pesquisa Sintegra para alagoas?
AL = CNPJ = 28311977000149
